name: build
on:
  push:


jobs:
  test:
    name: Run Tests and Code Coverage 📝
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }} 🐍
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies ⚙️
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install pytest pytest-cov build
    - name: Test with pytest ✅
      run: |
        pytest --cov=reproj
    - name: Coveralls 👖
      if: matrix.python-version == '3.11'
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        GITHUB_TOKEN: $COVERALLS_REPO_TOKEN
      run: |
        pip install coveralls
        coveralls
    - name: Try building a binary wheel and a source tarball 🚧
      run: |
        python -m build --sdist --wheel --outdir dist/ .
