name: build
on:
  push:
    paths-ignore:
      - 'examples/*'
      - 'README.md'
      - 'LICENSE.txt'
      - '.gitignore'


jobs:
  test:
    name: Run Tests and Code Coverage 📝
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4
    - name: Set up uv 🐍
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies ⚙️
      run: uv sync --extra test
    - name: Test with pytest ✅
      run: uv run pytest --cov=reproj
    - name: Coveralls 👖
      if: matrix.python-version == '3.13'
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: uvx coveralls
    - name: Try building a binary wheel and a source tarball 🚧
      run: uv build